version: '3'

services:
    app:
        build: .docker/php
        container_name: laravel-app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: laravel-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: laravel-db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=cooking
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin
        container_name: laravel-phpmyadmin
        ports:
            - 8081:80
        links:
            - db
        networks:
            - app-network
        depends_on:
            - db
        environment:
            PMA_HOST: db

    redis:
        image: redis:alpine
        container_name: laravel-redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge